export const baseUri = "https://mysocializer.herokuapp.com";
export const loading =
  "data:image/gif;base64,R0lGODlhEAAQAPIAAP///wAAAMLCwkJCQgAAAGJiYoKCgpKSkiH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQuaW5mbwAh+QQJCgAAACwAAAAAEAAQAAADMwi63P4wyklrE2MIOggZnAdOmGYJRbExwroUmcG2LmDEwnHQLVsYOd2mBzkYDAdKa+dIAAAh+QQJCgAAACwAAAAAEAAQAAADNAi63P5OjCEgG4QMu7DmikRxQlFUYDEZIGBMRVsaqHwctXXf7WEYB4Ag1xjihkMZsiUkKhIAIfkECQoAAAAsAAAAABAAEAAAAzYIujIjK8pByJDMlFYvBoVjHA70GU7xSUJhmKtwHPAKzLO9HMaoKwJZ7Rf8AYPDDzKpZBqfvwQAIfkECQoAAAAsAAAAABAAEAAAAzMIumIlK8oyhpHsnFZfhYumCYUhDAQxRIdhHBGqRoKw0R8DYlJd8z0fMDgsGo/IpHI5TAAAIfkECQoAAAAsAAAAABAAEAAAAzIIunInK0rnZBTwGPNMgQwmdsNgXGJUlIWEuR5oWUIpz8pAEAMe6TwfwyYsGo/IpFKSAAAh+QQJCgAAACwAAAAAEAAQAAADMwi6IMKQORfjdOe82p4wGccc4CEuQradylesojEMBgsUc2G7sDX3lQGBMLAJibufbSlKAAAh+QQJCgAAACwAAAAAEAAQAAADMgi63P7wCRHZnFVdmgHu2nFwlWCI3WGc3TSWhUFGxTAUkGCbtgENBMJAEJsxgMLWzpEAACH5BAkKAAAALAAAAAAQABAAAAMyCLrc/jDKSatlQtScKdceCAjDII7HcQ4EMTCpyrCuUBjCYRgHVtqlAiB1YhiCnlsRkAAAOwAAAAAAAAAAAA==";
export const LOGIN = "LOGIN";
export const _LOGIN_SUCCESS = "_LOGIN_SUCCESS";
export const _LOGIN_FAIL = "_LOGIN_FAIL";
export const SEARCH = "SEARCH";
export const _SEARCH_SUCCESS = "_SEARCH_SUCCESS";
export const _SEARCH_FAIL = "_SEARCH_FAIL";
export const GETUSER = "GETUSER";
export const _GETUSER_SUCCESS = "_GETUSER_SUCCESS";
export const _GETUSER_FAIL = "_GETUSER_FAIL";
export const LOGOUT = "LOGOUT";
export const CHANGEPASSWORD = "CHANGEPASSWORD";
export const _CHANGEPASSWORD_SUCCESS = "_CHANGEPASSWORD_SUCCESS";
export const _CHANGEPASSWORD_FAIL = "_CHANGEPASSWORD_FAIL";
